---

- name: containerization | add docker0 interface to public firewall zone
  ansible.builtin.include_role:
    name: tcharl.ansible_routing
  vars:
    firewalld_zones:
      - name: "{{ ansible_containerization_firewall_zone }}"
        nics:
          - "{{ ansible_containerization_docker_network_interface }}"
    virtual_hosts: []
