---
- name: containerization | create volumes
  ansible.builtin.import_role:
    name: tcharl.ansible_volumes
  when: standalone_role

- name: containerization | install prerequisite - firewalld
  package:
    name: firewalld
    state: present
  become: true

# tasks file for docker
- name: containerization | start firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
  become: true

- name: containerization | create directory
  ansible.builtin.file:
    path: "{{ ansible_containerization_configuration_folder }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: containerization | install prerequisite
  ansible.builtin.package:
    name: xfsprogs
    state: present
  become: true

- name: containerization | check docker volume is formatted in xfs
  ansible.builtin.shell: "xfs_info {{ ansible_containerization_docker_mountpoint }} | grep -c 'ftype=1'"
  become: yes
  register: mountedxfs
  ignore_errors: true
  changed_when: no

- name: containerization | copy filesystem driver
  ansible.builtin.copy:
    src: daemon.json
    dest: "{{ ansible_containerization_daemon_configuration_file }}"
    owner: root
    group: root
    mode: 0640
  become: true
  notify: containerization | restart service
  when: not mountedxfs is failed

- name: containerization | copy execution driver
  ansible.builtin.copy:
    src: exec-daemon.json
    dest: "{{ ansible_containerization_daemon_configuration_file }}"
    owner: root
    group: root
    mode: 0640
  become: true
  notify: containerization | restart service
  when: mountedxfs is failed

- name: containerization | install docker
  ansible.builtin.import_role:
    name: geerlingguy.docker
  become: true

- name: containerization | install python-docker
  ansible.builtin.package:
    name: python3-docker
    state: present
  become: true

- name: containerization | start
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  become: true
