---
# handlers file for docker

- name: containerization | service restart
  ansible.builtin.systemd:
    name: docker
    daemon_reload: yes
    state: restarted
  become: yes
  listen: containerization | restart service
