---
# handlers file for docker

- name: Handler | service restart
  ansible.builtin.systemd:
    name: docker
    daemon_reload: yes
    state: restarted
  delay: 6
  retries: 4
  register: res
  until: res is success
  become: yes
  listen: containerization | restart service
